### ISSUE TITLE
Minimum setup to use *.module.less

### ISSUE THREAD

**Issue by NitelPhyoe** [SolidZORO/mkn#1]
I use Typescript
My setup are
//next.config.js
const withAntdLess = require("next-plugin-antd-less");
const path = require("path");

module.exports = withAntdLess({
	lessVarsFilePath: path.join(__dirname, "./styles/antd-custom.less"),
	cssLoaderOptions: {
		esModule: false,
		sourceMap: false,
		modules: {
			mode: "local",
		},
	},

	// Other NextConfig Here...
	webpack(config) {
		return config;
	},
});

//.babelrc
{
    "presets": [
        "next/babel"
    ],
    "plugins": [
        [
            "import",
            {
                "libraryName": "antd",
                "style": true
            }
        ]
    ]
}

**Comment by SolidZORO** [comment]
so?

**Comment by NitelPhyoe** [comment]
with this setup i can't use *.module.less in *.tsx 

![image](https://user-images.githubusercontent.com/45162993/101308104-74fe0400-3877-11eb-866f-b6f80baef3ee.png)

**Comment by SolidZORO** [comment]
https://github.com/SolidZORO/mkn/blob/17bfdb3e093bc9bcd78f122e594e695f02d04a8e/typings/custom-typings.d.ts#L3

add this types file to your project.
